### ISSUE TITLE
Random generator is always the same

### ISSUE THREAD

**Issue by dbaynard** [mmsbrggr/munihac-graph-coloring#6]
Get the generator

```haskell
λ> gen <- getStdGen
```

Take 5 random numbers between 0 and 10.

```haskell
λ> take 5 $ randomRs (0,10) gen
[7,0,1,10,3]
```

And again…

```haskell
λ> take 5 $ randomRs (0,10) gen
[7,0,1,10,3]
```

They are the same because the generator is identical.

Take a new generator…

```haskell
λ> gen1 <- getStdGen
```

And then the first 5 numbers are…

```haskell
λ> take 5 $ randomRs (0,10) gen1
[7,0,1,10,3]
```

The same!

The generator needs updating otherwise the random numbers will be the same. Reloading ghci reloads the random number generator, otherwise it must be done explicitly in code.

**Comment by mmsbrggr** [comment]
fixed
